FROM node:12.18.3-alpine3.9 as builder

WORKDIR /usr/src/app

COPY ./package*.json ./
RUN npm install -g nuxt
RUN npm install #--loglevel=verbose
COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY ./nginx/default.conf.prod /etc/nginx/conf.d/default.conf
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]

