
export enum ERRORS {
  BIN_INCORRECT=901,
  BIN_REQUIRED,
  CAPTCHA_INCORRECT,
  CAPTCHA_REQUIRED,
  IENAME_REQUIRED,
  IENAME_MINLENGTH,
  IIN_INCORRECT,
  IIN_REQUIRED,
  LLPNAME_REQUIRED,
  LLPNAME_MINLENGTH,
  PASSWORD_MINLENGTH,
  PASSWORD_REQUIRED,
  PASSWORDS_NOT_EQUAL,
  PHONE_INCORRECT,
	PHONE_REQUIRED,
	SMSCODE_NO_CHANCES,
	SMSCODE_WRONG,
  USERTYPE_REQUIRED,
  USERNAME_REQUIRED,
}

export const myException = (code: number): void => {
  throw new Error(ERRORS[code])
}
